CREATE TABLE usuarios(
 id BIGINT AUTO_INCREMENT PRIMARY KEY,
 login VARCHAR(100) UNIQUE NOT NULL,
 password VARCHAR(255) NOT NULL
);
CREATE TABLE topicos(
 id BIGINT AUTO_INCREMENT PRIMARY KEY,
 titulo VARCHAR(255) NOT NULL,
 mensaje TEXT NOT NULL,
 fecha_creacion DATETIME NOT NULL,
 status VARCHAR(50) NOT NULL,
 autor VARCHAR(255) NOT NULL,
 curso VARCHAR(255) NOT NULL
);